### ISSUE TITLE
Example Error

### ISSUE THREAD

**Issue by lbolanos** [NRules/NRules.Language#15]
The example returns 
Applied discount. Customer=John Doe, Discount=50
But the discount is 5.0

Thanks In advance

**Comment by snikolayev** [comment]
I just ran it, and it looks correct.
The rule says: 
```c#
    order.PercentDiscount = 5.0;
    Console.WriteLine("Applied discount. Customer={0}, Discount={1}", customer.Name, order.PercentDiscount);
```
And that prints:
```
Applied discount. Customer=John Doe, Discount=5
```
Am I missing something?
