### ISSUE TITLE
Provide a .NET Standard v2 compatible NuGet package

### ISSUE THREAD

**Issue by punitganshani** [NRules/NRules.Language#2]
The current NuGet package has a dependency on `.NET 4.5`, can you please provide a NuGet package that is compatible with `.NET Standard v2.0`

**Comment by snikolayev** [comment]
It's coming up soon. This package is dependent on Antlr4.Runtime. My understanding is that I need a version 4.6.5 of that package to add .NET standard support. They were recently in beta, and just now moved to a release candidate. Once they have a general release, I'll be able to add support for .NET standard here as well.

**Comment by punitganshani** [comment]
Any ETA on this?

**Comment by snikolayev** [comment]
Still waiting for the Antlr4 to support .net standard

**Comment by snikolayev** [comment]
.NET Standard target was added in 0.0.3 release
