### ISSUE TITLE
State of the project

### ISSUE THREAD

**Issue by Anamika1911** [NRules/NRules.Language#6]
This project looks promising and I was planning to start using this. Its home page mentions that it is in 'Initial phase'. Is it correct? Are you planning to add more features to it?

**Comment by snikolayev** [comment]
Yes, planning to add more features, but the amount of attention it receives depends on the public interest it generates.
Separately, please ask questions on the forum or gitter chat, and reserve issues for bug reports and feature requests.

**Comment by bossiep1** [comment]
.net core 2.2 - when trying:
var repository = new RuleRepository();
repository.AddNamespace("System");
repository.AddReference(Assembly.GetExecutingAssembly());
repository.LoadText("using ...");

I get:
MissingMethodException: Method not found: 'System.Collections.Generic.IEnumerable`1<NRules.RuleModel.Declaration> NRules.RuleModel.Builders.RuleElementBuilder.get_Declarations()'.
NRules.RuleSharp.RuleParserListener.EnterRuleFactMatch(RuleFactMatchContext context)

Any ideas? Nuget packages NRules 0.9.0, NRules.Fluent 0.9.0, NRules.RuleModel 0.9.0, NRules.RuleSharp 0.0.4, NRules.Runtime 0.9.0 and Antlr4.Runtime 4.6.6.

Thanks!
