### ISSUE TITLE
Add support for NRules 0.9.0+

### ISSUE THREAD

**Issue by bossiep1** [NRules/NRules.Language#7]
.net core 2.2 - when trying:
var repository = new RuleRepository();
repository.AddNamespace("System");
repository.AddReference(Assembly.GetExecutingAssembly());
repository.LoadText("using ...");

I get:
MissingMethodException: Method not found: 'System.Collections.Generic.IEnumerable`1<NRules.RuleModel.Declaration> NRules.RuleModel.Builders.RuleElementBuilder.get_Declarations()'.
NRules.RuleSharp.RuleParserListener.EnterRuleFactMatch(RuleFactMatchContext context)

Any ideas? Nuget packages NRules 0.9.0, NRules.Fluent 0.9.0, NRules.RuleModel 0.9.0, NRules.RuleSharp 0.0.4, NRules.Runtime 0.9.0 and Antlr4.Runtime 4.6.6.

Thanks!

**Comment by snikolayev** [comment]
NRules 0.9.0 changed some APIs, which causes the above error. I already made the necessary changes in this project to support NRules 0.9.0, but they haven't been released yet. Either build NRules.RuleSharp from develop branch or wait with the upgrade to 0.9.0 for a few days, as I'll be releasing NRules.RuleSharp 0.0.5 soon.
